<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function setorkeluar_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function setorkeluar_menu() {

	$items['setorkeluar'] = array (
      'title' => 'Penyetoran',
	  'description' => 'Daftar Penyetoran',
	  'title callback' => 'setorkeluararsip_title_callback',	  
      'page callback' => 'setorkeluar_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'notDKK',
      'weight' => 11,
      'file' => 'setorkeluar_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['setorkeluarsub'] = array (
      'title' => 'Setor Keluar',
	  'description' => 'Daftar Setor',
	  'title callback' => 'setorkeluararsip_title_callback',	  
      'page callback' => 'setorkeluarsub_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'notDKK',
      'weight' => 11,
      'file' => 'setorkeluarsub_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['setorkeluaredit'] = array (
      'title' => 'Sumbit Setor',
	  'description' => 'Sumbit Setor',
	  'title callback' => 'setorkeluararsip_title_callback',	  
      'page callback' => 'setorkeluarsubmit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'notDKK',
      'weight' => 11,
      'file' => 'setorkeluarsubmit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	

    	

	
    return $items;
}


function setorkeluarantrian_title_callback() {
    return t('Antrian SPM Gaji');
}

function setorkeluar_title_callback() {
	return t('Arsip Setoran');
}

function setorkeluararsip_title_callback() {
    return t('Setoran Keluar');
}

